scope({c0_Cloud:124, c0_Feature:124, c0_Usability:124});
defaultScope(1);
intRange(-8, 7);
stringLength(16);

c0_Feature = Abstract("c0_Feature");
c0_Usability = c0_Feature.addChild("c0_Usability").withCard(1, 1);
c0_Cloud = c0_Feature.addChild("c0_Cloud").withCard(1, 1);
c0_FQAs = Abstract("c0_FQAs").withGroupCard(1);
c0_Security = c0_FQAs.addChild("c0_Security").withCard(0, 1).withGroupCard(1);
c0_Encryption = c0_Security.addChild("c0_Encryption").withCard(0, 1);
c0_EncryptionAlgorithms = c0_Encryption.addChild("c0_EncryptionAlgorithms").withCard(1, 1).withGroupCard(1, 1);
c0_Asymmetric = c0_EncryptionAlgorithms.addChild("c0_Asymmetric").withCard(0, 1).withGroupCard(1, 1);
c0_RSA = c0_Asymmetric.addChild("c0_RSA").withCard(0, 1);
c0_DSA = c0_Asymmetric.addChild("c0_DSA").withCard(0, 1);
c0_ECDSA = c0_Asymmetric.addChild("c0_ECDSA").withCard(0, 1);
c0_Symmetric = c0_EncryptionAlgorithms.addChild("c0_Symmetric").withCard(0, 1).withGroupCard(1, 1);
c0_AES = c0_Symmetric.addChild("c0_AES").withCard(0, 1);
c0_DESede = c0_Symmetric.addChild("c0_DESede").withCard(0, 1);
c0_Blowfish = c0_Symmetric.addChild("c0_Blowfish").withCard(0, 1);
c0_DES = c0_Symmetric.addChild("c0_DES").withCard(0, 1);
c0_KeySize = c0_Encryption.addChild("c0_KeySize").withCard(0, 1);
c0_EncryptionImplementations = c0_Encryption.addChild("c0_EncryptionImplementations").withCard(1, 1).withGroupCard(1, 1);
c0_JavaxCrypto = c0_EncryptionImplementations.addChild("c0_JavaxCrypto").withCard(0, 1);
c0_BouncyCastle = c0_EncryptionImplementations.addChild("c0_BouncyCastle").withCard(0, 1);
c0_EncryptionOperations = c0_Encryption.addChild("c0_EncryptionOperations").withCard(1, 1).withGroupCard(1, 1);
c0_Encrypt = c0_EncryptionOperations.addChild("c0_Encrypt").withCard(0, 1);
c0_Decrypt = c0_EncryptionOperations.addChild("c0_Decrypt").withCard(0, 1);
c0_Mode = c0_Encryption.addChild("c0_Mode").withCard(1, 1).withGroupCard(1, 1);
c0_CBC = c0_Mode.addChild("c0_CBC").withCard(0, 1);
c0_ECB = c0_Mode.addChild("c0_ECB").withCard(0, 1);
c0_CFB = c0_Mode.addChild("c0_CFB").withCard(0, 1);
c0_CTR = c0_Mode.addChild("c0_CTR").withCard(0, 1);
c0_CTS = c0_Mode.addChild("c0_CTS").withCard(0, 1);
c0_Padding = c0_Encryption.addChild("c0_Padding").withCard(1, 1).withGroupCard(1, 1);
c0_PKCS5 = c0_Padding.addChild("c0_PKCS5").withCard(0, 1);
c0_PKCS1 = c0_Padding.addChild("c0_PKCS1").withCard(0, 1);
c0_OAEP = c0_Padding.addChild("c0_OAEP").withCard(0, 1);
c0_Authentication = c0_Security.addChild("c0_Authentication").withCard(0, 1);
c0_AuthenticationImplementations = c0_Authentication.addChild("c0_AuthenticationImplementations").withCard(1, 1).withGroupCard(1, 1);
c0_JAAS = c0_AuthenticationImplementations.addChild("c0_JAAS").withCard(0, 1);
c0_SpringSecurity = c0_AuthenticationImplementations.addChild("c0_SpringSecurity").withCard(0, 1);
c0_AuthenticationOperations = c0_Authentication.addChild("c0_AuthenticationOperations").withCard(1, 1);
c0_Authenticate = c0_AuthenticationOperations.addChild("c0_Authenticate").withCard(1, 1);
c0_AuthenticationMechanism = c0_Authentication.addChild("c0_AuthenticationMechanism").withCard(1, 1).withGroupCard(1, 1);
c0_UserPassword = c0_AuthenticationMechanism.addChild("c0_UserPassword").withCard(0, 1);
c0_DigitalCertificate = c0_AuthenticationMechanism.addChild("c0_DigitalCertificate").withCard(0, 1);
c0_PseudonymousCertificate = c0_DigitalCertificate.addChild("c0_PseudonymousCertificate").withCard(0, 1);
c0_Biometric = c0_AuthenticationMechanism.addChild("c0_Biometric").withCard(0, 1);
c0_SocialID = c0_AuthenticationMechanism.addChild("c0_SocialID").withCard(0, 1);
c0_Pin = c0_AuthenticationMechanism.addChild("c0_Pin").withCard(0, 1);
c0_MatrixCode = c0_AuthenticationMechanism.addChild("c0_MatrixCode").withCard(0, 1);
c0_PasswordLength = c0_Authentication.addChild("c0_PasswordLength").withCard(0, 1);
c0_PasswordType = c0_Authentication.addChild("c0_PasswordType").withCard(0, 1).withGroupCard(1, 1);
c0_Numeric = c0_PasswordType.addChild("c0_Numeric").withCard(0, 1);
c0_Alphanumeric = c0_PasswordType.addChild("c0_Alphanumeric").withCard(0, 1);
c0_SpecialChars = c0_PasswordType.addChild("c0_SpecialChars").withCard(0, 1);
c0_LimitedSession = c0_Authentication.addChild("c0_LimitedSession").withCard(0, 1);
c0_AuthenticationLogging = c0_Authentication.addChild("c0_AuthenticationLogging").withCard(0, 1);
c0_AnonymousUser = c0_Authentication.addChild("c0_AnonymousUser").withCard(0, 1);
c0_Hashing = c0_Security.addChild("c0_Hashing").withCard(0, 1);
c0_HashingImplementations = c0_Hashing.addChild("c0_HashingImplementations").withCard(1, 1).withGroupCard(1, 1);
c0_JavaSecurityMessageDigest = c0_HashingImplementations.addChild("c0_JavaSecurityMessageDigest").withCard(0, 1);
c0_Guava = c0_HashingImplementations.addChild("c0_Guava").withCard(0, 1);
c0_HashingOperations = c0_Hashing.addChild("c0_HashingOperations").withCard(1, 1);
c0_Hash = c0_HashingOperations.addChild("c0_Hash").withCard(1, 1);
c0_HashingAlgorithms = c0_Hashing.addChild("c0_HashingAlgorithms").withCard(1, 1).withGroupCard(1, 1);
c0_MD5 = c0_HashingAlgorithms.addChild("c0_MD5").withCard(0, 1);
c0_SHA1 = c0_HashingAlgorithms.addChild("c0_SHA1").withCard(0, 1);
c0_SHA256 = c0_HashingAlgorithms.addChild("c0_SHA256").withCard(0, 1);
c0_SHA512 = c0_HashingAlgorithms.addChild("c0_SHA512").withCard(0, 1);
c0_Confidentiality = c0_Security.addChild("c0_Confidentiality").withCard(0, 1);
c0_Privacy = c0_Security.addChild("c0_Privacy").withCard(0, 1);
c0_Integrity = c0_Security.addChild("c0_Integrity").withCard(0, 1);
c0_Non_Repudiation = c0_Security.addChild("c0_Non_Repudiation").withCard(0, 1);
c1_Usability = c0_FQAs.addChild("c1_Usability").withCard(0, 1).withGroupCard(1);
c0_Logging = c1_Usability.addChild("c0_Logging").withCard(0, 1);
c0_LoggingOperations = c0_Logging.addChild("c0_LoggingOperations").withCard(1, 1);
c0_Log = c0_LoggingOperations.addChild("c0_Log").withCard(1, 1);
c0_LoggingImplementations = c0_Logging.addChild("c0_LoggingImplementations").withCard(1, 1).withGroupCard(1, 1);
c0_Log4J = c0_LoggingImplementations.addChild("c0_Log4J").withCard(0, 1);
c0_LogBack = c0_LoggingImplementations.addChild("c0_LogBack").withCard(0, 1);
c0_JavaUtilLogging = c0_LoggingImplementations.addChild("c0_JavaUtilLogging").withCard(0, 1);
c0_SimpleImplementationSLF4J = c0_LoggingImplementations.addChild("c0_SimpleImplementationSLF4J").withCard(0, 1);
c0_Handler = c0_Logging.addChild("c0_Handler").withCard(1, 1).withGroupCard(1, 1);
c0_ConsoleLog = c0_Handler.addChild("c0_ConsoleLog").withCard(0, 1);
c0_FileLog = c0_Handler.addChild("c0_FileLog").withCard(0, 1);
c0_DatabaseLog = c0_Handler.addChild("c0_DatabaseLog").withCard(0, 1);
c0_Format = c0_Logging.addChild("c0_Format").withCard(1, 1).withGroupCard(1, 1);
c0_TXT = c0_Format.addChild("c0_TXT").withCard(0, 1);
c0_XML = c0_Format.addChild("c0_XML").withCard(0, 1);
c0_HTML = c0_Format.addChild("c0_HTML").withCard(0, 1);
c0_JSON = c0_Format.addChild("c0_JSON").withCard(0, 1);
c0_Level = c0_Logging.addChild("c0_Level").withCard(1, 1).withGroupCard(1);
c0_Trace = c0_Level.addChild("c0_Trace").withCard(0, 1);
c0_Debug = c0_Level.addChild("c0_Debug").withCard(0, 1);
c0_Info = c0_Level.addChild("c0_Info").withCard(0, 1);
c0_Warning = c0_Level.addChild("c0_Warning").withCard(0, 1);
c0_Error = c0_Level.addChild("c0_Error").withCard(0, 1);
c0_CypheredMessages = c0_Logging.addChild("c0_CypheredMessages").withCard(0, 1);
c0_HistoryLog = c0_Logging.addChild("c0_HistoryLog").withCard(0, 1);
c0_ErrorLog = c0_Logging.addChild("c0_ErrorLog").withCard(0, 1);
c0_TraceFile = c0_ErrorLog.addChild("c0_TraceFile").withCard(0, 1);
c0_ContextualHelp = c1_Usability.addChild("c0_ContextualHelp").withCard(0, 1);
c0_ContextualHelpOperations = c0_ContextualHelp.addChild("c0_ContextualHelpOperations").withCard(1, 1);
c0_ShowHelp = c0_ContextualHelpOperations.addChild("c0_ShowHelp").withCard(1, 1);
c0_ContextualHelpImplementations = c0_ContextualHelp.addChild("c0_ContextualHelpImplementations").withCard(1, 1);
c0_JavaWizardAPI = c0_ContextualHelpImplementations.addChild("c0_JavaWizardAPI").withCard(1, 1);
c0_HelpType = c0_ContextualHelp.addChild("c0_HelpType").withCard(1, 1).withGroupCard(1);
c0_Tutorial = c0_HelpType.addChild("c0_Tutorial").withCard(0, 1);
c0_Wizard = c0_HelpType.addChild("c0_Wizard").withCard(0, 1);
c0_UserType = c0_ContextualHelp.addChild("c0_UserType").withCard(1, 1).withGroupCard(1);
c0_Beginner = c0_UserType.addChild("c0_Beginner").withCard(0, 1);
c0_Intermediate = c0_UserType.addChild("c0_Intermediate").withCard(0, 1);
c0_Advanced = c0_UserType.addChild("c0_Advanced").withCard(0, 1);
c0_Expert = c0_UserType.addChild("c0_Expert").withCard(0, 1);
c0_AuthenticatedUser = c0_ContextualHelp.addChild("c0_AuthenticatedUser").withCard(0, 1);
c0_ExecutionControl = c1_Usability.addChild("c0_ExecutionControl").withCard(0, 1);
c0_ExecutionControl_1 = c0_ExecutionControl.addChild("c0_ExecutionControl_1").withCard(1, 1).withGroupCard(1);
c0_Undo = c0_ExecutionControl_1.addChild("c0_Undo").withCard(0, 1);
c0_Redo = c0_ExecutionControl_1.addChild("c0_Redo").withCard(0, 1);
c0_Cancel = c0_ExecutionControl_1.addChild("c0_Cancel").withCard(0, 1);
c0_GoBack = c0_ExecutionControl_1.addChild("c0_GoBack").withCard(0, 1);
c0_Shortcuts = c0_ExecutionControl.addChild("c0_Shortcuts").withCard(0, 1);
c0_Internationalization = c1_Usability.addChild("c0_Internationalization").withCard(0, 1);
c0_Locale = c0_Internationalization.addChild("c0_Locale").withCard(1, 1);
c0_Feedback = c1_Usability.addChild("c0_Feedback").withCard(0, 1).withGroupCard(1);
c0_InteractionFeedback = c0_Feedback.addChild("c0_InteractionFeedback").withCard(0, 1);
c0_ProgressFeedback = c0_Feedback.addChild("c0_ProgressFeedback").withCard(0, 1);
c0_SystemStatusDisplay = c0_Feedback.addChild("c0_SystemStatusDisplay").withCard(0, 1);
c0_Alerts = c0_Feedback.addChild("c0_Alerts").withCard(0, 1);
c0_Persistence = c0_FQAs.addChild("c0_Persistence").withCard(0, 1).withGroupCard(1);
c0_FileStorage = c0_Persistence.addChild("c0_FileStorage").withCard(0, 1);
c0_FileStorageOperations = c0_FileStorage.addChild("c0_FileStorageOperations").withCard(1, 1).withGroupCard(1, 1);
c0_CreateFile = c0_FileStorageOperations.addChild("c0_CreateFile").withCard(0, 1);
c0_ModifyFile = c0_FileStorageOperations.addChild("c0_ModifyFile").withCard(0, 1);
c0_DeleteFile = c0_FileStorageOperations.addChild("c0_DeleteFile").withCard(0, 1);
c0_FileType = c0_FileStorage.addChild("c0_FileType").withCard(1, 1).withGroupCard(1, 1);
c0_Binary = c0_FileType.addChild("c0_Binary").withCard(0, 1);
c0_TXTFile = c0_FileType.addChild("c0_TXTFile").withCard(0, 1);
c0_XMLFile = c0_FileType.addChild("c0_XMLFile").withCard(0, 1);
c0_JSONFile = c0_FileType.addChild("c0_JSONFile").withCard(0, 1);
c0_FileStorageImplementations = c0_FileStorage.addChild("c0_FileStorageImplementations").withCard(1, 1);
c0_JavaIO = c0_FileStorageImplementations.addChild("c0_JavaIO").withCard(1, 1);
c0_TemporalFile = c0_FileStorage.addChild("c0_TemporalFile").withCard(0, 1);
c0_DatabaseStorage = c0_Persistence.addChild("c0_DatabaseStorage").withCard(0, 1);
c0_DatabaseStorageOperations = c0_DatabaseStorage.addChild("c0_DatabaseStorageOperations").withCard(1, 1).withGroupCard(1, 1);
c0_Store = c0_DatabaseStorageOperations.addChild("c0_Store").withCard(0, 1);
c0_Query = c0_DatabaseStorageOperations.addChild("c0_Query").withCard(0, 1);
c0_DatabaseStorageImplementations = c0_DatabaseStorage.addChild("c0_DatabaseStorageImplementations").withCard(1, 1).withGroupCard(1, 1);
c0_MySQL = c0_DatabaseStorageImplementations.addChild("c0_MySQL").withCard(0, 1);
c0_MongoDB = c0_DatabaseStorageImplementations.addChild("c0_MongoDB").withCard(0, 1);
c0_OracleDB = c0_DatabaseStorageImplementations.addChild("c0_OracleDB").withCard(0, 1);
c0_DatabaseType = c0_DatabaseStorage.addChild("c0_DatabaseType").withCard(1, 1).withGroupCard(1, 1);
c0_Relational = c0_DatabaseType.addChild("c0_Relational").withCard(0, 1);
c0_NoSQL = c0_DatabaseType.addChild("c0_NoSQL").withCard(0, 1);
c0_DataType = c0_DatabaseStorage.addChild("c0_DataType").withCard(1, 1).withGroupCard(1);
c0_Integers = c0_DataType.addChild("c0_Integers").withCard(0, 1);
c0_Strings = c0_DataType.addChild("c0_Strings").withCard(0, 1);
c0_Floats = c0_DataType.addChild("c0_Floats").withCard(0, 1);
c0_Objects = c0_DataType.addChild("c0_Objects").withCard(0, 1);
c0_SecureDatabase = c0_DatabaseStorage.addChild("c0_SecureDatabase").withCard(0, 1);
c0_ContextAwareness = c0_FQAs.addChild("c0_ContextAwareness").withCard(0, 1).withGroupCard(1);
c0_LocationAware = c0_ContextAwareness.addChild("c0_LocationAware").withCard(0, 1).withGroupCard(1);
c0_GPS = c0_LocationAware.addChild("c0_GPS").withCard(0, 1);
c0_WiFiLocation = c0_LocationAware.addChild("c0_WiFiLocation").withCard(0, 1);
c0_TimeAware = c0_ContextAwareness.addChild("c0_TimeAware").withCard(0, 1);
c0_DeviceAware = c0_ContextAwareness.addChild("c0_DeviceAware").withCard(0, 1).withGroupCard(1);
c0_BatteryStatus = c0_DeviceAware.addChild("c0_BatteryStatus").withCard(0, 1);
c0_IRSensor = c0_DeviceAware.addChild("c0_IRSensor").withCard(0, 1);
c0_UserAware = c0_ContextAwareness.addChild("c0_UserAware").withCard(0, 1);
c0_EnvironmentAware = c0_ContextAwareness.addChild("c0_EnvironmentAware").withCard(0, 1);
c0_Performance = c0_FQAs.addChild("c0_Performance").withCard(0, 1);
c0_Caching = c0_Performance.addChild("c0_Caching").withCard(1, 1);
c0_CachingOperations = c0_Caching.addChild("c0_CachingOperations").withCard(1, 1).withGroupCard(1, 1);
c0_CacheStore = c0_CachingOperations.addChild("c0_CacheStore").withCard(0, 1);
c0_CacheQuery = c0_CachingOperations.addChild("c0_CacheQuery").withCard(0, 1);
c0_CacheUpdate = c0_CachingOperations.addChild("c0_CacheUpdate").withCard(0, 1);
c0_CachingImplementations = c0_Caching.addChild("c0_CachingImplementations").withCard(1, 1).withGroupCard(1, 1);
c0_JavaCachingSystem = c0_CachingImplementations.addChild("c0_JavaCachingSystem").withCard(0, 1);
c0_Caffeine = c0_CachingImplementations.addChild("c0_Caffeine").withCard(0, 1);
c0_MaxSizeCache = c0_Caching.addChild("c0_MaxSizeCache").withCard(1, 1);
c0_CacheType = c0_Caching.addChild("c0_CacheType").withCard(1, 1).withGroupCard(1, 1);
c0_LocalCache = c0_CacheType.addChild("c0_LocalCache").withCard(0, 1);
c0_RemoteCache = c0_CacheType.addChild("c0_RemoteCache").withCard(0, 1);
c0_MaxLifeSeconds = c0_Caching.addChild("c0_MaxLifeSeconds").withCard(0, 1);
c0_EternalObjects = c0_Caching.addChild("c0_EternalObjects").withCard(0, 1);
c0_total_usability = c0_FQAs.addChild("c0_total_usability").withCard(0, 1);
c0_total_cloud = c0_FQAs.addChild("c0_total_cloud").withCard(0, 1);
c0_CP = Clafer("c0_CP").withCard(1, 1).withGroupCard(1);
c0_Usability.refToUnique(Int);
c0_Usability.addConstraint(greaterThanEqual(joinRef($this()), constant(0)));
c0_Cloud.refToUnique(Int);
c0_Cloud.addConstraint(greaterThanEqual(joinRef($this()), constant(0)));
c0_RSA.extending(c0_Feature);
c0_RSA.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_RSA.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_DSA.extending(c0_Feature);
c0_DSA.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_DSA.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_ECDSA.extending(c0_Feature);
c0_ECDSA.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_ECDSA.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_AES.extending(c0_Feature);
c0_AES.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_AES.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_DESede.extending(c0_Feature);
c0_DESede.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_DESede.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Blowfish.extending(c0_Feature);
c0_Blowfish.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Blowfish.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_DES.extending(c0_Feature);
c0_DES.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_DES.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_KeySize.extending(c0_Feature);
c0_KeySize.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_KeySize.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_JavaxCrypto.extending(c0_Feature);
c0_JavaxCrypto.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_JavaxCrypto.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_BouncyCastle.extending(c0_Feature);
c0_BouncyCastle.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_BouncyCastle.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Encrypt.extending(c0_Feature);
c0_Encrypt.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_Encrypt.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Decrypt.extending(c0_Feature);
c0_Decrypt.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_Decrypt.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_CBC.extending(c0_Feature);
c0_CBC.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_CBC.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_ECB.extending(c0_Feature);
c0_ECB.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_ECB.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_CFB.extending(c0_Feature);
c0_CFB.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_CFB.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_CTR.extending(c0_Feature);
c0_CTR.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_CTR.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_CTS.extending(c0_Feature);
c0_CTS.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_CTS.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_PKCS5.extending(c0_Feature);
c0_PKCS5.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_PKCS5.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_PKCS1.extending(c0_Feature);
c0_PKCS1.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_PKCS1.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_OAEP.extending(c0_Feature);
c0_OAEP.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_OAEP.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_JAAS.extending(c0_Feature);
c0_JAAS.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_JAAS.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_SpringSecurity.extending(c0_Feature);
c0_SpringSecurity.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_SpringSecurity.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Authenticate.extending(c0_Feature);
c0_Authenticate.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_Authenticate.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_UserPassword.extending(c0_Feature);
c0_UserPassword.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_UserPassword.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_PseudonymousCertificate.extending(c0_Feature);
c0_PseudonymousCertificate.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_PseudonymousCertificate.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Biometric.extending(c0_Feature);
c0_Biometric.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_Biometric.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_SocialID.extending(c0_Feature);
c0_SocialID.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(8)));
c0_SocialID.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Pin.extending(c0_Feature);
c0_Pin.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_Pin.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_MatrixCode.extending(c0_Feature);
c0_MatrixCode.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_MatrixCode.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_PasswordLength.extending(c0_Feature);
c0_PasswordLength.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(8)));
c0_PasswordLength.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Numeric.extending(c0_Feature);
c0_Numeric.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Numeric.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Alphanumeric.extending(c0_Feature);
c0_Alphanumeric.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_Alphanumeric.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_SpecialChars.extending(c0_Feature);
c0_SpecialChars.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_SpecialChars.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_LimitedSession.extending(c0_Feature);
c0_LimitedSession.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_LimitedSession.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_AuthenticationLogging.extending(c0_Feature);
c0_AuthenticationLogging.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_AuthenticationLogging.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_AnonymousUser.extending(c0_Feature);
c0_AnonymousUser.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_AnonymousUser.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_JavaSecurityMessageDigest.extending(c0_Feature);
c0_JavaSecurityMessageDigest.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_JavaSecurityMessageDigest.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Guava.extending(c0_Feature);
c0_Guava.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_Guava.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Hash.extending(c0_Feature);
c0_Hash.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_Hash.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_MD5.extending(c0_Feature);
c0_MD5.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_MD5.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_SHA1.extending(c0_Feature);
c0_SHA1.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_SHA1.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_SHA256.extending(c0_Feature);
c0_SHA256.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_SHA256.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_SHA512.extending(c0_Feature);
c0_SHA512.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_SHA512.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Confidentiality.extending(c0_Feature);
c0_Confidentiality.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Confidentiality.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Privacy.extending(c0_Feature);
c0_Privacy.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Privacy.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Integrity.extending(c0_Feature);
c0_Integrity.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_Integrity.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Non_Repudiation.extending(c0_Feature);
c0_Non_Repudiation.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_Non_Repudiation.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Log.extending(c0_Feature);
c0_Log.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_Log.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Log4J.extending(c0_Feature);
c0_Log4J.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_Log4J.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_LogBack.extending(c0_Feature);
c0_LogBack.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_LogBack.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_JavaUtilLogging.extending(c0_Feature);
c0_JavaUtilLogging.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_JavaUtilLogging.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_SimpleImplementationSLF4J.extending(c0_Feature);
c0_SimpleImplementationSLF4J.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_SimpleImplementationSLF4J.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_ConsoleLog.extending(c0_Feature);
c0_ConsoleLog.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_ConsoleLog.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_FileLog.extending(c0_Feature);
c0_FileLog.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_FileLog.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_DatabaseLog.extending(c0_Feature);
c0_DatabaseLog.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_DatabaseLog.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_TXT.extending(c0_Feature);
c0_TXT.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_TXT.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_XML.extending(c0_Feature);
c0_XML.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_XML.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_HTML.extending(c0_Feature);
c0_HTML.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_HTML.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_JSON.extending(c0_Feature);
c0_JSON.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_JSON.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Trace.extending(c0_Feature);
c0_Trace.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_Trace.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Debug.extending(c0_Feature);
c0_Debug.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_Debug.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Info.extending(c0_Feature);
c0_Info.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Info.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Warning.extending(c0_Feature);
c0_Warning.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_Warning.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Error.extending(c0_Feature);
c0_Error.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_Error.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_CypheredMessages.extending(c0_Feature);
c0_CypheredMessages.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_CypheredMessages.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_HistoryLog.extending(c0_Feature);
c0_HistoryLog.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_HistoryLog.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_TraceFile.extending(c0_Feature);
c0_TraceFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_TraceFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_ShowHelp.extending(c0_Feature);
c0_ShowHelp.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_ShowHelp.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_JavaWizardAPI.extending(c0_Feature);
c0_JavaWizardAPI.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_JavaWizardAPI.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Tutorial.extending(c0_Feature);
c0_Tutorial.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Tutorial.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Wizard.extending(c0_Feature);
c0_Wizard.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_Wizard.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Beginner.extending(c0_Feature);
c0_Beginner.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_Beginner.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Intermediate.extending(c0_Feature);
c0_Intermediate.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_Intermediate.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Advanced.extending(c0_Feature);
c0_Advanced.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Advanced.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Expert.extending(c0_Feature);
c0_Expert.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_Expert.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_AuthenticatedUser.extending(c0_Feature);
c0_AuthenticatedUser.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_AuthenticatedUser.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Undo.extending(c0_Feature);
c0_Undo.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_Undo.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Redo.extending(c0_Feature);
c0_Redo.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_Redo.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Cancel.extending(c0_Feature);
c0_Cancel.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Cancel.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_GoBack.extending(c0_Feature);
c0_GoBack.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_GoBack.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Shortcuts.extending(c0_Feature);
c0_Shortcuts.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_Shortcuts.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Locale.extending(c0_Feature);
c0_Locale.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_Locale.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_InteractionFeedback.extending(c0_Feature);
c0_InteractionFeedback.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_InteractionFeedback.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_ProgressFeedback.extending(c0_Feature);
c0_ProgressFeedback.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_ProgressFeedback.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_SystemStatusDisplay.extending(c0_Feature);
c0_SystemStatusDisplay.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(8)));
c0_SystemStatusDisplay.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Alerts.extending(c0_Feature);
c0_Alerts.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Alerts.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_CreateFile.extending(c0_Feature);
c0_CreateFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_CreateFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_ModifyFile.extending(c0_Feature);
c0_ModifyFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_ModifyFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_DeleteFile.extending(c0_Feature);
c0_DeleteFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_DeleteFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Binary.extending(c0_Feature);
c0_Binary.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_Binary.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_TXTFile.extending(c0_Feature);
c0_TXTFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(8)));
c0_TXTFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_XMLFile.extending(c0_Feature);
c0_XMLFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_XMLFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_JSONFile.extending(c0_Feature);
c0_JSONFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_JSONFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_JavaIO.extending(c0_Feature);
c0_JavaIO.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_JavaIO.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_TemporalFile.extending(c0_Feature);
c0_TemporalFile.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_TemporalFile.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Store.extending(c0_Feature);
c0_Store.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_Store.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Query.extending(c0_Feature);
c0_Query.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(8)));
c0_Query.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_MySQL.extending(c0_Feature);
c0_MySQL.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_MySQL.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_MongoDB.extending(c0_Feature);
c0_MongoDB.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_MongoDB.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_OracleDB.extending(c0_Feature);
c0_OracleDB.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_OracleDB.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Relational.extending(c0_Feature);
c0_Relational.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_Relational.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_NoSQL.extending(c0_Feature);
c0_NoSQL.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_NoSQL.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Integers.extending(c0_Feature);
c0_Integers.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(9)));
c0_Integers.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Strings.extending(c0_Feature);
c0_Strings.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(4)));
c0_Strings.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Floats.extending(c0_Feature);
c0_Floats.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(5)));
c0_Floats.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_Objects.extending(c0_Feature);
c0_Objects.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_Objects.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_SecureDatabase.extending(c0_Feature);
c0_SecureDatabase.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_SecureDatabase.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_GPS.extending(c0_Feature);
c0_GPS.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_GPS.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_WiFiLocation.extending(c0_Feature);
c0_WiFiLocation.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_WiFiLocation.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_TimeAware.extending(c0_Feature);
c0_TimeAware.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_TimeAware.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_BatteryStatus.extending(c0_Feature);
c0_BatteryStatus.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_BatteryStatus.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_IRSensor.extending(c0_Feature);
c0_IRSensor.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_IRSensor.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_UserAware.extending(c0_Feature);
c0_UserAware.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_UserAware.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_EnvironmentAware.extending(c0_Feature);
c0_EnvironmentAware.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_EnvironmentAware.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_CacheStore.extending(c0_Feature);
c0_CacheStore.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_CacheStore.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_CacheQuery.extending(c0_Feature);
c0_CacheQuery.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(2)));
c0_CacheQuery.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_CacheUpdate.extending(c0_Feature);
c0_CacheUpdate.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(3)));
c0_CacheUpdate.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_JavaCachingSystem.extending(c0_Feature);
c0_JavaCachingSystem.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_JavaCachingSystem.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_Caffeine.extending(c0_Feature);
c0_Caffeine.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_Caffeine.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_MaxSizeCache.extending(c0_Feature);
c0_MaxSizeCache.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_MaxSizeCache.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_LocalCache.extending(c0_Feature);
c0_LocalCache.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(1)));
c0_LocalCache.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(0)));
c0_RemoteCache.extending(c0_Feature);
c0_RemoteCache.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(10)));
c0_RemoteCache.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_MaxLifeSeconds.extending(c0_Feature);
c0_MaxLifeSeconds.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(6)));
c0_MaxLifeSeconds.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_EternalObjects.extending(c0_Feature);
c0_EternalObjects.addConstraint(equal(joinRef(join($this(), c0_Usability)), constant(7)));
c0_EternalObjects.addConstraint(equal(joinRef(join($this(), c0_Cloud)), constant(1)));
c0_total_usability.refToUnique(Int);
c0_FQAs.addConstraint(implies(some(join($this(), c0_total_usability)), equal(joinRef(join($this(), c0_total_usability)), minimum(joinRef(join(global(c0_Feature), c0_Usability))))));
c0_total_cloud.refToUnique(Int);
c0_FQAs.addConstraint(implies(some(join($this(), c0_total_cloud)), equal(joinRef(join($this(), c0_total_cloud)), minimum(joinRef(join(global(c0_Feature), c0_Cloud))))));
Constraint(or(some(join(join(global(c0_FQAs), c0_ContextAwareness), c0_TimeAware)), none(join(join(join(global(c0_FQAs), c0_ContextAwareness), c0_DeviceAware), c0_BatteryStatus))));
Constraint(or(some(join(join(join(global(c0_FQAs), c1_Usability), c0_Feedback), c0_Alerts)), none(join(join(join(global(c0_FQAs), c0_ContextAwareness), c0_DeviceAware), c0_BatteryStatus))));
Constraint(or(some(join(join(global(c0_FQAs), c0_Persistence), c0_FileStorage)), none(join(join(join(join(global(c0_FQAs), c1_Usability), c0_Logging), c0_ErrorLog), c0_TraceFile))));
Constraint(or(none(join(join(join(join(global(c0_FQAs), c1_Usability), c0_Logging), c0_LoggingImplementations), c0_SimpleImplementationSLF4J)), none(join(join(join(join(global(c0_FQAs), c1_Usability), c0_Logging), c0_Format), c0_XML))));
Constraint(or(none(join(join(join(global(c0_FQAs), c1_Usability), c0_ContextualHelp), c0_AuthenticatedUser)), some(join(join(global(c0_FQAs), c0_Security), c0_Authentication))));
Constraint(or(none(join(join(join(global(c0_FQAs), c1_Usability), c0_Logging), c0_ErrorLog)), some(join(join(join(join(global(c0_FQAs), c1_Usability), c0_Logging), c0_Level), c0_Error))));
Constraint(or(none(join(join(join(global(c0_FQAs), c1_Usability), c0_Logging), c0_HistoryLog)), some(join(join(join(join(global(c0_FQAs), c1_Usability), c0_Logging), c0_Level), c0_Trace))));
c0_CP.extending(c0_FQAs);
